aviabird/gringotts

- test/gateways/monei_test.exs
* This just increases coverage stats.
> Tests for void, refund, capture

- .travis.yml
> Makes Travis run integration tests

- README.md
> Fix example config in README

- lib/gringotts/gateways/cams.ex
- test/gateways/cams_test.exs
- test/mocks/cams_mock.exs
It is not finished yet, still working on it.
1. Altered library cams.ex 
2. Added Mock Tests for Purchase method.
Checklist:-
> Added Test for purchase, authorize, refund ,capture & void methods

- .gitignore
- lib/gringotts.ex
- lib/gringotts/gateways/authorize_net.ex
- test/gateways/authorize_net_test.exs
- test/mocks/authorize_net_mock.exs
The pull request covers the following:
1. Modified all the  camel case keys in the opts keyword to snake case.
2. Modified docs as per monei specifications for all the basic functions, added examples.
3. Added mock responses for testing all the functions.
4. Added tests for authorize net library for authorize, capture, refund, void, store and unstore.
> AuthorizeNet tests with improved docs

- .gitignore
- README.md
- lib/gringotts.ex
- lib/gringotts/application.ex
- lib/gringotts/credit_card.ex
- lib/gringotts/gateways/authorize_net.ex
- lib/gringotts/gateways/cams.ex
- lib/gringotts/gateways/monei.ex
- lib/gringotts/gateways/paymill.ex
- lib/gringotts/gateways/stripe.ex
- lib/gringotts/gateways/wire_card.ex
- mix.exs
- test/gateways/authorize_net_test.exs
- test/gateways/cams_test.exs
- test/gateways/monei_test.exs
- test/gateways/stripe_test.exs
- test/gringotts_test.exs
- test/mocks/authorize_net_mock.exs
- test/mocks/cams_mock.exs
* Some changes in the README.md
* Doc improvements 
* More comprehensive test coverage
> Fixes and test cases for gateways

- mix.exs
* Also re-ordered the deps list, groups runtime deps on top.
> Added version for inch_ex

- lib/gringotts/gateways/cams.ex
- test/gateways/cams_test.exs
- test/mocks/cams_mock.exs
1. Added 404 & 400 status code response handling.
2. Added network error handling.
> Cams : Added error response handling

- lib/gringotts/gateways/authorize_net.ex
- lib/gringotts/response.ex
- test/gateways/authorize_net_test.exs
- test/mocks/authorize_net_mock.exs
The pull request covers the following:
**Tests**
Added `tests` for authorize net library for the functions authorize, capture, refund, void, store and unstore.
Added `mock responses` for the authorize net library for functions authorize, capture, refund, void, store and unstore.
**ResponeHandler**
Created a `ResponseHandle` module to handle responses for the AuthorizeNet library. Created methods for parsing success and error responses for the gateway. Added the private methods assist in  creation of the Response struct.
> Anet Response

- lib/mix/new.ex
- templates/integration.eex
- templates/mock_response.eex
- templates/test.eex
Pull request covers a mix task to generate the following files for the gateway:
1. Test
2. Integration Test
3. Mock Responses.
> Mix task for tests, mocks and integration

- lib/gringotts/gateways/monei.ex
- test/gateways/monei_test.exs
- test/integration/gateways/monei_test.exs
* Mock tests now use the worker.
* Corrected capture args order.
> [monei] Fix doc example typos, and mock tests

- lib/mix/new.ex
- templates/gateway.eex
- templates/integration.eex
- templates/mock_response.eex
- templates/test.eex
* fixes some patterns in function clauses
* argument order was wrong in `capture`
> [mix-task] Fixed arg order in capture

- lib/gringotts/gateways/global_collect.ex
- mix.exs
- test/gateways/global_collect_test.exs
- test/mocks/global_collect_mock.exs
Following functions have been implemented as of now:
1)Authorize
2)Capture
3)Purchase
4)Refund
5)Void
With the test cases and docs added for each of them.
> Global Collect payment gateway integration .

- lib/gringotts/credit_card.ex
- lib/gringotts/gateways/bogus.ex
- lib/gringotts/gateways/monei.ex
- lib/gringotts/response.ex
- mix.lock
- test/gateways/bogus_test.exs
- test/gateways/monei_test.exs
- test/integration/gateways/monei_test.exs
Adapted MONEI for the new struct.
Also refactored `commit` and `respond` in MONEI to make them more readable.
> Introduces `Response.t` with docs

- lib/gringotts/gateways/mercadopago.ex
- test/gateways/mercadopago_test.exs
- test/integration/gateways/mercadopago_test.exs
- test/mocks/mercadopago_mock.exs
Created helper functions, body for HTTPoison commands and response functions for authorize.
> Mercadopago authorize/3 

- lib/gringotts/gateways/trexle.ex
- test/gateways/trexle_test.exs
* Trexle does not seem to provide fraud risk, AVS, CVV validation results. **There are no docs for this.**
> Adapted Trexle for new `Response.t`

- lib/gringotts/gateways/global_collect.ex
- test/gateways/global_collect_test.exs
- test/mocks/global_collect_mock.exs
* `credo` issues resolved 
* Fixed some layout issues
* Corrected `amount` in examples
* Ran the elixir 1.6 code formatter
- Used sigils in mocks
* Removed unnecessary functions
- Reduced arity of `add_money`
* Refactored Timex usage
* Removed a test on `validate_config` as it is already tested.
> [global-collect] Layout, docs improvements and code refactors

- lib/gringotts/gateways/securion_pay.ex
- test/integration/gateways/securion_pay_test.exs
Implemented 'capture/3' and added integration test cases along with it.
> [SecurionPay] Implemented `capture/3`

- lib/gringotts/gateways/securion_pay.ex
- test/integration/gateways/securion_pay_test.exs
`void/2`
---------
* Cancels a pre-authorized charge(transaction).
* SecurionPay does not support partial cancellation.
Tests
------
* Added integration tests for `void/2` using Exvcr.
Docs
-----
* Mentioned the expiration of stand-alone authorized transaction
* Added docs for `void/2`
* Marked `capture/2` and `void/2` as implemented in module docs
> [SecurionPay] Implemented `void/2`

- mix.exs
- test/gateways/authorize_net_test.exs
- test/gateways/cams_test.exs
- test/gateways/global_collect_test.exs
- test/gateways/paymill_test.exs
- test/gateways/trexle_test.exs
- test/gateways/wire_card_test.exs
- test/mocks/authorize_net_mock.ex
- test/mocks/cams_mock.ex
- test/mocks/global_collect_mock.ex
- test/mocks/paymill_mock.ex
- test/mocks/trexle_mock.ex
Integration and mock tests are added, along with code updates.
> Paymill mock

- lib/gringotts/gateways/sagepay.ex
- test/integration/gateways/sagepay_test.exs
Changed the structure of opts for purchase
> [Sagepay] Implemented Purchase

- lib/gringotts/gateways/sagepay.ex
- test/integration/gateways/sagepay_test.exs
Implements the `refund/3` function.
Integration test added.
> [SagePay] Implemented Refund

- lib/gringotts/gateways/sagepay.ex
- test/integration/gateways/sagepay_test.exs
Implemented Void function
Implemented Void test cases
> [Sagepay]  Implemented `void/2`

- LICENSE
- README.md
The attribution was long due to @joshnuss's [`commerce_billing`](https://github.com/joshnuss/commerce_billing).
Thanks to #177 for jolting :zap: us into action! :slightly_smiling_face:
> Add project attribution in README

- .github/workflows/elixir.yml
- .tool-versions
- lib/gringotts/gateways/paymill.ex
- mix.exs
- test/gateways/openpay_test.exs
This PR adds
- asdf config for current elixir/erlang verions
- updates version to 1.1.1
- adds github ci for test and format check
> Release 1.1.1
