aviabird/gringotts

lib/gringotts.ex
lib/gringotts/gateways/authorize_net.ex
lib/gringotts/worker.ex
test/gateways/authorize_net_test.exs
test/gateways/monei_test.exs
test/mocks/authorize_net_mock.exs
test/test_helper.exs

Fix for #31 
1. **Setting a global  `config`  for 'prod' or 'test' mode.**
This is a new feature provided as a `:global_config` for the lib to set the url for making requests to the 
gateway.  The configuration is done in the application as follows for test: 
``` elixir
config :gringotts, :global_config,
mode: :test
```
and for prod
```elixir
config :gringotts, :global_config,
mode: :prod
```
It would be available as following in `opts[:config: [mode: :test ]]`. Made necessary checks on this to 
change the api for making calls to the gateway.
2. **Added test for purchase method for authorize net payment gateway using mock.**
The new strategy is to use `mock` library for testing the gateways. The strategy was devised keeping 
in mind the fact that any fields required in the test should be …

Authorize net test purchase

---

lib/gringotts/gateways/monei.ex
test/gateways/monei_test.exs
test/integration/gateways/monei_test.exs

* Added a small configuration guide. There's also a broken link to a "Getting Started" guide, which we should fix soon.
* Examples share some context, and can be followed in an `iex` session.
* `commit` and `respond` are now private.
- Marked a test on `respond` as `:skip` because `respond` is now private, and cannot be tested :(
* Integration tests were failing ever since the lib rename. Fixed that. They were not caught because #13 is still open.

Added examples and config to docs

---

lib/gringotts/credit_card.ex
lib/gringotts/gateways/authorize_net.ex
lib/gringotts/gateways/cams.ex
lib/gringotts/gateways/monei.ex
lib/gringotts/gateways/paymill.ex
lib/gringotts/gateways/wire_card.ex

If you read up on how to document Structs, you'll realise that `CreditCard`, (the module) should not be used as a "type" -- because it is a module, just a bunch of functions. This is related to the confusion between `String` and `String.t`.
Composite types must be defined using `@type`. This helps static analysers like Dialyser to actually perform type-checking.
In the excellent [swoosh library](https://github.com/swoosh/swoosh/search?utf8=%E2%9C%93&q=type+t+%3A%3A+%25__MODULE__%7Btype&type=).
References:
https://www.reddit.com/r/elixir/comments/4v2ss2/help_me_understand_types_in_documentation_specs/
http://elixir-recipes.github.io/types/type-checking/
https://hexdocs.pm/elixir/typespecs.html#user-defined-types
https://stackoverflow.com/questions/29977776/what-does-type-t-module-mean-in-el …

Creditcard docs

---

lib/gringotts/application.ex
test/gringotts_test.exs

* This test checks if an `ArgumentError` exception is raised when some config is missing.
* Also removes an unused variable from `application.ex`.

Adds a test for validate_config

---

lib/gringotts/gateways/monei.ex
test/gateways/monei_test.exs

* Grouped tests using `describe`
* Made stylisitic improvements as suggested by `credo`

Credo powered improvements for monei

---

README.md
lib/gringotts/gateways/stripe.ex
test/gateways/stripe_test.exs

* refactor code to accept payment with card details and pass address in options.
* refactor current test cases according to the above refactored code.

Separate payment into card and address

---

README.md
lib/gringotts.ex
lib/gringotts/gateways/authorize_net.ex
lib/gringotts/gateways/cams.ex
lib/gringotts/gateways/monei.ex
lib/gringotts/gateways/paymill.ex
lib/gringotts/gateways/stripe.ex
test/gringotts_test.exs
test/integration/gateways/monei_test.exs

Removed `:payment_worker` argument to be explicitly given while calling the public Api.
Fixes #7.
Following changes were made.
1. Removed the worker argument from public api.
2. Removed the payment worker from the examples of gateway files.
**Earlier** the api needed to be called this way. 
```elixir
Gringotts.purchase(:payment_worker, Gringotts.Gateways.Stripe, 5, @payment, @options)
```
**Now** it needs to be this way.
```elixir
Gringotts.purchase(Gringotts.Gateways.Stripe, 5, @payment, @options)
```

Modified Gringotts Public Api

---

README.md
lib/gringotts/credit_card.ex
lib/gringotts/gateways/stripe.ex

* add guard clause when source params is token or customer
* trim name since it will contain the extra space when first_name or last_name is not passed in card struct.
*  don't change the struct into map, access card params from struct only
* change stripe docs according to new credit card and address struct
* change expiration year in README.md

Stripe gateway minor fixes and docs update

---

lib/gringotts/gateways/trexle.ex
test/gateways/trexle_test.exs

Following a proper format for Address and Credit Card using structs to maintain the consistency.

Using Address and Credit Card struct

---

lib/mix/new.ex
templates/gateway.eex

* Generates a barebones implementation for the gateway, the following are included:
- docs and specs for all public methods
- hints on implementation of the methods
- suggests 2 private methods: `respond` and `commit`
* Also generates docs dynamically,
- If no `required_keys` are supplied when the task is run, the docs do not contain an empty table.
- Otherwise, the table and config examples include the keys.
```
mix gringotts.new GlobalCollect --module GlobalCollect
```
And, don't change the suggested URL (because apparently, it's valid).
You could play with the `required_keys`, keep it empty or keep it: `api_key_id, secret_api_key, merchant_id`

Adds a super useful mix task: gringotts.new

---

README.md
lib/gringotts/gateways/monei.ex
test/gateways/monei_test.exs
test/integration/gateways/monei_test.exs

[monei] Implements optional/extra params

---

lib/gringotts/gateways/authorize_net.ex
test/gateways/authorize_net_test.exs

Used Gringotts.Money to check for money params.
Added doc for Authorize Net currency support.
Currently, I have to convert `Decimal` to a lossy `float` because a string amount is not accepted by the Authorize.Net  lib. Will raise an issue with Authorize.Net regarding this.

Money Integration with Authorize.Net

---

lib/gringotts/gateways/authorize_net.ex
test/gateways/authorize_net_test.exs
test/mocks/authorize_net_mock.exs

* Adds a new Response field: authorization.
- It is set to `["transactionResponse"]["transId"]`
* Uses `Gringotts.Money.to_string` instead of converting to lossy Float
* doc examples updated (authorize, capture, purchase)
* Improved all docs, http links and made most lines fit 80 columns
* Ran the elixir 1.6 formatter
- Used the `~s` sigil in mocks
- Also removed an invisible Unicode codepoint from mock strings
Fixes #90 and Fixes #91

[ANet] Corrected use of money protocol and examples 

---

lib/gringotts/gateways/trexle.ex
test/gateways/trexle_test.exs
test/mocks/trexle_mock.exs

Uses `Money.to_integer` as Trexle works in cents.
* token and message added to `Response`
* fixed doc examples
* removed unnecessary tests and mocks
Ran the elixir 1.6 code formatter
* Used `~s` sigils in mocks

[trexle] Adds Money protocol 

---

lib/gringotts/gateways/cams.ex
test/gateways/cams_test.exs
test/mocks/cams_mock.exs

* Modified methods according to money protocol
* Fixes #21, Fixes #26 and Fixes #28

[CAMS] Adds money protocol

---

lib/gringotts/gateways/authorize_net.ex
mix.exs
mix.lock
test/gateways/authorize_net_test.exs

- Updated dependency `xml_builder`. The new `generate/2` provides a `format: :none | :indented` option.
- `:format` is set to `:none` to produce "minified" network requests.
* This is almost a complete rewrite to reduce code duplication.
- `check_response_type/1` was acting as guard that matched only against some response types. It did not handle the scenario when a non-supported response would be obtained. It really served no purpose.
- `check_response_type` -> `extract_gateway_response`
+ This guards as well as fetches, previously the fetch was being done multiple times.
* Moved all response handling inside the `ResponseHandler`.
* Since we now have a struct, and want to deprecate `:success`, `Response.success/1` and  `Response.error/1`, helpers now act on structs.
* `errorCode` and …

[ANet] Adapt for new `Response.t`

---

CHANGELOG.md
CONTRIBUTING.md
README.md
lib/gringotts/adapter.ex
lib/gringotts/gateways/authorize_net.ex
lib/gringotts/gateways/bogus.ex
lib/gringotts/gateways/cams.ex
lib/gringotts/gateways/monei.ex
lib/gringotts/gateways/trexle.ex
lib/mix/new.ex
mix.exs
mix.lock
templates/mock_response.eex
templates/test.eex
test/gateways/bogus_test.exs

* Improved `Adapter` `moduledoc` and bogus gateway
- Fixes #24 (bogus gateway)
- `bogus_test` also uses `Money` protocol now
* `validate_config` docs explain its operation.
* mix task: `gringotts.new`
- Improved docs
- Better module name suggestion
- Filename can be specified on the CLI with the `-f` flag
* Added changelog and contributing guide.
* Correct "amount" in examples to ex_money

Adds changelog, contributing guide and improves mix task

---

lib/gringotts/gateways/securion_pay.ex

Captures a pre-authorized transcation from the customer.
Successful request returns a charge object that was captured.
It takes payment_id, amount and opts as arguments.

Implemented SecurionPay.capture/3

---

lib/gringotts/gateways/cams.ex
test/gateways/cams_test.exs

* Refactored `ResponseHandler`
* Removed unnecessary one-liners which avoids unnecessary appends.
* Used better variable and function names.
* CAMS now parses AVS and CVV response - that was missing till now.
* **CAMS always returned an `:ok` tuple!** Fixed that. (Look at the old tests)
* Added `reason` to `Resonse.t` in cases of error. 
* Removes unnecessary `parse` clause.

[CAMS] Adapt for new Response.t

---

README.md
lib/gringotts.ex
lib/gringotts/adapter.ex
templates/gateway.eex
templates/integration.eex
templates/test.eex

* Closes #150 
- validates that the config is a list. The `reduce` will fail if it's not a `keyword` list.
* Closes #136
* Closes #80

Add clause to catch/handle bad config format

---

lib/mix/new.ex

This pull requests refactors some of the code in the generator.
The command `mix credo -a` showed a list of warnings, and some of them were in the `new.ex` file.
The resolved warnings:
```
┃ [F] → Function is too complex (CC is 11, max is 9).
┃       lib/mix/new.ex:50:7 #(Mix.Tasks.Gringotts.New.run)
┃ [F] → Pipe chain should start with a raw value.
┃       lib/mix/new.ex:139 #(Mix.Tasks.Gringotts.New.prompt_with_suggestion)
┃ [F] → Pipe chain should start with a raw value.
┃       lib/mix/new.ex:102 #(Mix.Tasks.Gringotts.New.run)
┃ [F] → Pipe chain should start with a raw value.
┃       lib/mix/new.ex:97 #(Mix.Tasks.Gringotts.New.run)
```
This pull request also fixes issue #158

Small refactoring to fix credo linting warnings

---

lib/gringotts/gateways/authorize_net.ex

The access key used to grab the item id from an item is `:item_id` [here](https://github.com/aviabird/gringotts/blob/dev/lib/gringotts/gateways/authorize_net.ex#L632), but the example on line 232 uses `:itemId`

Fix option name in authorize/3 example

---

.travis.yml

If it works, remove 1.5 and use 1.6 and 1.7 instead.
With 1.7 developers can use ElixirLS

Test elixir 1.7.4 on travisCI
